version: 2.1

executors:

      
jobs:
  build1:
    executor: 
      docker:
        image: circleci/node
    steps:
      - checkout  
      - run: echo "this is build1"
  build2:
    executor: 
      docker:
        image: circleci/node
    steps:
      - checkout  
      - run: echo "this is build2"
      
workflows:
  build-1-workflow:
    jobs:
      build1
  build-2-workflow:
    jobs:
      build2
