version: 2.1
jobs:
  build-test:
    docker:
      - image: cimg/node:12.17
    steps:
      - run: echo "run tests"
  package:
    docker:
      - image: cimg/node:12.17
    steps:
      - run: echo "package"
  deploy:
    docker:
      - image: cimg/node:12.17
    steps:
      - run: echo "deploy"

workflows:
  commit:
    jobs:
      - build-test
      
  package:
    when:
      or:
        - equal: [ test, << pipeline.git.tag  >> ]
        - equal: [ test1, << pipeline.git.tag  >> ]
    jobs:
      - package:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - package:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - package:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - package:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - package:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - package:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
            
  deploy:
    jobs:
      - deploy  

