version: 2
jobs:
  # This checks out the code, installs dependencies, and persists node_modules
  build:
    working_directory: ~/project/app
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      # Save the entire `~/project/app` directory to the workspace for this run
      - persist_to_workspace:
          root: ~/project
          paths:
            - app
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  node-tests:
    jobs:
      - build