version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.17
    steps:
      - checkout
      - run: echo 'success'
workflows:
  build:
    when: << pipeline.git.branch >>
    jobs:
      - build
      #test
