version: 2.1

executors:
  cclearly-build:
    machine:
      image: circleci/classic:201703-01
      
jobs:
  build:
    executor: cclearly-build
    steps:
      - checkout    
      - run: sudo apt-get update
      - run: sudo apt-get install dpkg
      - run: sudo apt-get -y install --reinstall ca-certificates
      - run: docker run --rm ubuntu:14.04.5 bash -c 'apt-key update; apt-get update; apt-get install -y odbc-postgresql'
      
      
workfows:
  build:
    jobs:
      - build
