version: 2.1
jobs:
  build-test:
    docker:
      - image: cimg/node:12.17
    steps:
      - run: echo << pipeline.git.tag >>

workflows:
  commit:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/

              #test24
