version: 2
jobs:
  # This checks out the code, installs dependencies, and persists node_modules
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "this is the build job"
  build_and_push_prd_image: 
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "this is the build_and_push_prd_image job"

workflows:
  version: 2
  auto refresh:
    # triggers:
    #   - schedule:
    #       cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
    #       filters:
    #         branches:
    #           only:
    #             - main
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build_and_push_prd_image:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+?$/ # v1.1.1 (API Production)