version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.17
    steps:
      - checkout
      - run:
          command: sudo npm install
      - run: echo 'success'
      - run: |
          ls /home/circleci/.config/git
          ls /home/circleci/.config/git/attributes
workflows:
  build:
    jobs:
      - build
      #test
