version: 2
jobs:
  build:
    docker:
    - image: elixir:1.9-alpine
    steps:
    - checkout
    - run: echo docker version
    - run:
        name: update docker
        command: |
          docker update
    - run: echo docker version
workflows:
  version: 2
  build:
    jobs:
    - build