version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:14.15.0
    working_directory: ~/test/test_directory
    steps:
      - checkout
      - run: echo 'success'
      - run: ls
  build:
    jobs:
      - build
      #test
