version: 2.1

orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: cimg/android:29.0
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - run: echo "Ruby 2.7 has been installed"
      - run: echo 'success'
workflows:
  build:
    jobs:
      - build
      #test 2
