version: 2.1

orbs:
  orb-project: orb-space/orb-project@1

executors:
  orbi-ex: orb-project/default
  image-name:
    docker:
      - image: "cimg/node:14.17.5"
  orbi-rust: orb-project/rust

parameters:
  test-param:
    type: boolean
    default: false

jobs:
  build:
    executor: orb-project/rust
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - orb-project/greet

workflows:
  build:
    jobs:
      - build
          # filters:
          #   # ignore any commit on any branch by default
          #   branches:
          #     ignore: /.*/
          #   # only act on version tags
          #   tags:
          #     only: /^v.*/
          #test



# version: 2.1

# # executors:
# #   machine-ubuntu:
# #     machine:
# #       image: ubuntu-2004:202104-01
# jobs:
#   build-test:
#     # resource_class: xlarge
#     # executor: machine-ubuntu
#     docker:
#       - image: cimg/node:16.5.0
#     steps:
#       #- run: yarn version
#       #https://app.circleci.com/pipelines/github/creditornot/wolt-ios-merchant/<< pipeline.number >>/workflows/${CIRCLE_WORKFLOW_ID}
#       - run: echo https://app.circleci.com/pipelines/github/hud-code/test-circleci-repo/<< pipeline.number >>/workflows/${CIRCLE_WORKFLOW_ID}
#       - run: echo << pipeline.number >>
# workflows:
#   commit:
#     jobs:
#       - build-test # test
# conditional-workflow:
#   when:
#     and: # All must be true to trigger
#       - equal: [ main, << pipeline.git.branch >> ]
#       - not: << pipeline.parameters.test-param >>