version: 2.1

restore_npm_cache: &restore_npm_cache
  name: Restore npm cache
  keys:
    - npm-packages-v1-{{ checksum "package-lock.json" }}

save_npm_cache: &save_npm_cache
  name: Save npm cache
  key: npm-packages-v1-{{ checksum "package-lock.json" }}
  paths:
    - ./node_modules/

executors:
  avrios-core:
    working_directory: /tmp/frontend-service
    docker:
      # Need to use the java image because we need the mvn command
      - image: circleci/openjdk:16-jdk-buster-node-browsers

jobs:
  build:
    executor: avrios-core

    steps:
      - checkout

      - restore_cache: *restore_npm_cache

      # - restore_cache:
      #     name: Restore maven cache
      #     keys:
      #       - maven-packages-{{ checksum "pom.xml" }}

      - save_cache: *save_npm_cache

      # - save_cache:
      #     name: Save maven cache
      #     key: maven-packages-{{ checksum "pom.xml" }}
      #     paths:
      #       - ~/.m2/

workflows:
  version: 2

  on_commit:
    jobs:
      - build
