version: 2.1

# executors:
#   machine-ubuntu:
#     machine:
#       image: ubuntu-2004:202104-01
jobs:
  build-test:
    # resource_class: xlarge
    # executor: machine-ubuntu
    docker:
      - image: cimg/node:16.5.0
    steps:
      #- run: yarn version
      - run: echo https://circleci.com/workflow-run/{workflow id}
workflows:
  commit:
    jobs:
      - build-test # test
