# version: 2.1

# # executors:
# #   machine-ubuntu:
# #     machine:
# #       image: ubuntu-2004:202104-01
# jobs:
#   build-test:
#     # resource_class: xlarge
#     # executor: machine-ubuntu
#     docker:
#       - image: cimg/node:16.5.0
#     steps:
#       #- run: yarn version
#       #https://app.circleci.com/pipelines/github/creditornot/wolt-ios-merchant/<< pipeline.number >>/workflows/${CIRCLE_WORKFLOW_ID}
#       - run: echo https://app.circleci.com/pipelines/github/hud-code/test-circleci-repo/<< pipeline.number >>/workflows/${CIRCLE_WORKFLOW_ID}
#       - run: echo << pipeline.number >>
# workflows:
#   commit:
#     jobs:
#       - build-test # test

version: 2

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date