version: 2.1

executors:
  cclearly-build:
    machine:
      image: ubuntu-2004:202104-01
      
jobs:
  build:
    executor: cclearly-build
    steps:
      - checkout    
      - run: sudo apt-get update
      - run: sudo apt-get install dpkg
      - run: sudo apt-get -y install unixodbc unixodbc-dev odbc-postgresql #test
      
      
workfows:
  build:
    jobs:
      - build
