version: 2.1
jobs:
  build:
    docker:
      - image: suitepad/circleci-primary-docker
    steps:
      - checkout
      - run: echo 'success'
      - run: |
          echo ls /home/circleci/.config/git
          echo ls /home/circleci/.config/git/attributes
workflows:
  build:
    jobs:
      - build
      #test
