version: 2.1
jobs:
  build:
    docker:
      - image: suitepad/circleci-primary-docker
    steps:
      - checkout
      - run: echo 'success'
      - setup_remote_docker:
          docker_layer_caching: true
workflows:
  build:
    jobs:
      - build
      #test