version: 2.1

      
jobs:
  build1:
    docker:
      - image: circleci/node
    steps:
      - checkout  
      - run: echo "this is build1"
  build2: 
    docker:
      - image: circleci/node
    steps:
      - checkout  
      - run: echo "this is build2"
      
parameters:
  ci_commit_label:
    type: boolean
    default: false
      
workflows:
  build-1-workflow:
    when: << pipeline.parameters.ci_commit_label >>
    jobs:
      - build1:
          filters:
            branches:
              only:
                - main
  build-2-workflow:
    when:
      not: << pipeline.parameters.ci_commit_label >>
    jobs:
      - build2:
          filters:
            branches:
              only:
                - main
