version: 2.1

orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: cimg/android:29.0
    steps:
      - checkout
      - run: echo 'success'
workflows:
  build:
    jobs:
      - build
      #test 2
