version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: echo 'success'
      - run: |
          rustup toolchain install nightly
          rustup default nightly
          cargo build --release --all-features
workflows:
  build:
    jobs:
      - build
      #test