version: 2.1
jobs:
  # This checks out the code, installs dependencies, and persists node_modules
  build:
    docker:
      - image: circleci/python:3.9.4
    steps:
      - checkout
      - run: echo "this is the build job"
      - when:
          condition:
            matches:
              pattern: "^3\\.9\\.\\*"    # can't do "^3\\.9" only due to (likely) circleci regex matching bug
              value: 3.9.45.7
          steps:
            - run: echo "This worked correctly 3.9.4"
  build_and_push_prd_image: 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "this is the build_and_push_prd_image job"

workflows:
  version: 2
  auto refresh:
    # triggers:
    #   - schedule:
    #       cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
    #       filters:
    #         branches:
    #           only:
    #             - /.*/
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - build_and_push_prd_image:
          requires:
            - build
          filters:
            branches:
              only: cron