version: 2.1

orbs:
  latest: orb-space/orb-project@1
  hello: orb-space/test-orb-7@dev:alpha

executors:
  php:
    docker:
      - image: "circleci/php@sha256:7a3c8dbd2a39b3af732eb541bb5bc8a180d9ff083fc3cc9bd050b6a2c36898dd"
  mysql:
    docker:
      - image: "circleci/mysql@sha256:c29fd8f4428cf873c2031549efa946ee86ac36135686e660c6030dfffe35d48f"
  php7-3:
    docker:
      - image: "circleci/php@sha256:baf464ba817a90d5088c7e87805518a6cc2f666cb869b2f1e53d0bb6baea1d1f"

parameters:
  test-param:
    type: boolean
    default: false
  test-string:
    type: string
    default: ""

jobs:
  build:
    executor: php7-3
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo "<< pipeline.git.tag >>"
      # - latest/greet
      # - hello/hello-zach
  build2:
    executor: php
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
  build3:
    executor: mysql
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
workflows:
  build:
    when:
      not:
        equal: [<< pipeline.git.tag >>, ]
    jobs:
      - build
  build2:
    jobs:
      - build2
          # filters:
          #   # ignore any commit on any branch by default
          #   branches:
          #     ignore: /.*/
          #   # only act on version tags
          #   tags:
          #     only: /^v.*/
          #test test test



# version: 2.1

# # executors:
# #   machine-ubuntu:
# #     machine:
# #       image: ubuntu-2004:202104-01
# jobs:
#   build-test:
#     # resource_class: xlarge
#     # executor: machine-ubuntu
#     docker:
#       - image: cimg/node:16.5.0
#     steps:
#       #- run: yarn version
#       #https://app.circleci.com/pipelines/github/creditornot/wolt-ios-merchant/<< pipeline.number >>/workflows/${CIRCLE_WORKFLOW_ID}
#       - run: echo https://app.circleci.com/pipelines/github/hud-code/test-circleci-repo/<< pipeline.number >>/workflows/${CIRCLE_WORKFLOW_ID}
#       - run: echo << pipeline.number >>
# workflows:
#   commit:
#     jobs:
#       - build-test # test
# conditional-workflow:
#   when:
#     and: # All must be true to trigger
#       - equal: [ main, << pipeline.git.branch >> ]
#       - not: << pipeline.parameters.test-param >>