version: 2.1

# executors:
#   machine-ubuntu:
#     machine:
#       image: ubuntu-2004:202104-01
jobs:
  build-test:
    # resource_class: xlarge
    # executor: machine-ubuntu
    docker:
      image: "cimg/node"
    steps:
      - run: yarn version
workflows:
  commit:
    jobs:
      - build-test # test
