version: 2.1
jobs:
  test-and-build:
    macos:
      xcode: 12.4.0
    steps:
      - checkout
      - run: xcodebuild -resolvePackageDependencies
      - run: echo hi
      - run: brew --version
      - run: carthage version
workflows:
  test-and-build-adhoc:
    jobs:
      - test-and-build