version: 2.1

executors:
  machine-ubuntu:
    machine:
      image: ubuntu-2004:202104-01
jobs:
  build-test:
    resource_class: xlarge
    executor: machine-ubuntu
    steps:
      - run:
          command: |
            while true; do
              sleep 5
              ps auxwwf
              echo "======"
            done
          background: true
      - checkout
      - run: echo "success"

workflows:
  commit:
    jobs:
      - build-test # test
