version: 2.1

parameters:
  run_by_api:
    type: boolean
    default: false

jobs:
  regular:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "I was run normally"

  api-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "I was run by API"

workflows:
  normal:
    jobs:
      - regular

  api-workflow:
    when: << pipeline.parameters.run_by_api >> # Add condition to execute this workflow when condition-workflow is equal to true
    jobs:
      - api-job