# Original config.yml file:
version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3
  android: circleci/android@1.0.3

jobs:
  release_android:
    docker:
      - image: circleci/android:api-29 # ruby 2.6.1
    steps:
      - checkout
      - android/install-ndk:
          ndk-version: android-ndk-r21e
          # find newer versions here: https://developer.android.com/ndk/downloads

workflows:
  release_android:
    jobs:
      - release_android
