version: 2.1

executors:

      
jobs:
  build1:
    docker:
      - image: circleci/node
    steps:
      - checkout  
      - run: echo "this is build1"
  build2: 
    docker:
      - image: circleci/node
    steps:
      - checkout  
      - run: echo "this is build2"
      
workflows:
  build-1-workflow:
#     when:
#       or:
#         - equal: ["[reset ci]", << pipeline.parameters.ci_commit_label >>]
#         - equal: ["[ci reset]", << pipeline.parameters.ci_commit_label >>]
    jobs:
      - build1:
          filters:
            branches:
              only:
                - main
  build-2-workflow:
    jobs:
      - build2:
          filters:
            branches:
              only:
                - main
