version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo 'success'
workflows:
  build:
    jobs:
      - build
      #test 2323
      #test change like 'no-cache'