version: 2.1
jobs:
  build-test:
    machine:
      - image: ubuntu-2004:202104-01
    steps:
      - run:
          command: |
            while true; do
              sleep 5
              ps auxwwf
              echo "======"
            done
          background: true
      - run: checkout
      - run: echo "success"

workflows:
  commit:
    jobs:
      - build-test
